### PR TITLE
Issue #1684: Invalid query generated using OracleDriver for filter with Option column.

### LINKED ISSUE #1684: Invalid query generated using OracleDriver for filter with Option column
While using Slick 3.1.1 with OracleDriver for the following query definition:
```scala
table1 joinRight table2 on (_.key1 === _.key2))
.filter {
case (_, table2ValueOption) => table2ValueOption.parameter.map(_ === searchingValue).getOrElse(false)
case _ => false.bind
}
.result
```

I've received the following sql query:
```sql
select ... where {fn ifnull((case when (s11."parameter" is null) then null else (case when (s11."parameter" = '{searchingValue}') then 1 else 0 end) end),0)}
```

and in result the sql error:
> [2017-01-23 09:31:31] [42000][920] ORA-00920: invalid relational operator

I've tried the same with both freeslick and the slick-extentions but there were no difference. Across the whole application we use DatabaseConfig[JdbcProfile] abstraction, having the exact driver defined in the configuration by using two parameters:
```
driver = "freeslick.OracleProfile$"
db {
  ...
  driver = "oracle.jdbc.OracleDriver"
}
```

I'm still not sure if that's some general problem with Slick support for Oracle database or I'm using it wrong.

### PR DESCRIPTION
**Pull request by alexFrankfurt**
Adds test and fixes #1684 
Giving value by default and comparing with boolean like [here](https://github.com/alexFrankfurt/slick/commit/80e3224390ec11a1ad4b491d88d8e3ddb5847208#diff-4f6a4460f0646720349ec80039ba7e1eR24) wasn't working either. This PR implements fix for that case as well.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @alexFrankfurt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kubukoz** [comment]
Hi @alexFrankfurt, would you be willing to finish this? If you don't have time, let me know and I'll try to take over and bring this to completion.

File: slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/OptionBooleanTest.scala [hunk 1]
```diff
@@ -0,0 +1,29 @@
+package com.typesafe.slick.testkit.tests
+
+import com.typesafe.slick.testkit.util.{AsyncTest, JdbcTestDB}
+import slick.jdbc.OracleProfile
+
+class OptionBooleanTest extends AsyncTest[JdbcTestDB] {
+  lazy val oracleProfile = tdb.profile.asInstanceOf[OracleProfile]
```
Comment (WellingR) [inline slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/OptionBooleanTest.scala]: Can we change this test so that we can execute this for all databases? This is something that should work regardless of the profile that is used.

Comment (alexFrankfurt) [reply slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/OptionBooleanTest.scala]: Yes, I've made appropriate changes.

**Comment by Alnaimi-** [comment]
issue was reported 2 years ago now, and the fix was proposed 5 months ago. Can we please get this in?

**Comment by kubukoz** [comment]
@szeiger?

**Comment by jorgedfbranco** [comment]
Guys, any news regarding this? We just migrated from squeryl to slick only to find that Slick can't properly handle boolean values..?

**Comment by hvesalai** [comment]
@kubukoz thank you for the PR

**Comment by kubukoz** [comment]
@hvesalai not my PR ;)

**Comment by alexFrankfurt** [comment]
Happy to make slick better 👍

**Comment by hvesalai** [comment]
So sorry guys. Credit where credit is due. Thank you @alexFrankfurt !
