### PR TITLE
Fixing #966

### LINKED ISSUE #966: Scala's Slick with multiple PK insertOrUpdate() throws exception ERROR: syntax error at end of input
I am using Scala' Slick and PostgreSQL. And I am working well with tables with single PK. Now I need to use a table with multiple PKs:

```
case class Report(f1: DateTime,
    f2: String,
    f3: Double)

class Reports(tag: Tag) extends Table[Report](tag, "Reports") {
    def f1 = column[DateTime]("f1")
    def f2 = column[String]("f2")
    def f3 = column[Double]("f3")

    def * = (f1, f2, f3) <> (Report.tupled, Report.unapply)
    def pk = primaryKey("pk_report", (f1, f2))
}

val reports = TableQuery[Reports]
```

when I have empty table and use reports.insert(report) it works well. But when I use reports.insertOrUpdate(report) I receive and exception:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 76
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
    at ....
```

What am I doing wrong? How to fix it?

Thanks in advance.

PS. I tried workaround - tried to implement "if exist update else insert" logic by:

```
  val len = reports.withFilter(_.f1 === report.f1).withFilter(_.f2 === report.f2).length.run.toInt
                    if(len == 1) {
                        println("Update: " + report)
                        reports.update(report)
                    } else {
                        println("Insert: " + report)
                        reports.insert(report)
                    }
```

But I still get exception on update:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_report"
  Detail: Key ("f1", f2)=(2014-01-31 04:00:00, addon_io.aha.connect) already exists.
```

### PR DESCRIPTION
**Pull request by tminglei**
This patch is trying to fix #966 by including `Table.primary(..)` defined primary keys when generating upsert sql.

It's not perfect. As the [comment](https://github.com/slick/slick/issues/966#issuecomment-231499500) said, it remained a derby related issue.

Pls review and give your suggestions.

_Thanks!_

### CODE REVIEW

File: slick/src/main/scala/slick/jdbc/JdbcStatementBuilderComponent.scala [hunk 1]
```diff
@@ -529,7 +529,13 @@ trait JdbcStatementBuilderComponent { self: JdbcProfile =>
 
   /** Builder for upsert statements, builds standard SQL MERGE statements by default. */
   class UpsertBuilder(ins: Insert) extends InsertBuilder(ins) {
-    protected lazy val (pkSyms, softSyms) = syms.toSeq.partition(_.options.contains(ColumnOption.PrimaryKey))
+    /* NOTE: pk defined by using method `primaryKey` and pk defined with `PrimaryKey` can only have one,
+             here we let table ddl to help us ensure this. */
+    private lazy val funcDefinedPKs = table.profileTable.asInstanceOf[Table[_]].primaryKeys
```
Comment (cvogt) [inline slick/src/main/scala/slick/jdbc/JdbcStatementBuilderComponent.scala]: why is asInstanceOf[Table[_]] needed?

Comment (tminglei) [inline slick/src/main/scala/slick/jdbc/JdbcStatementBuilderComponent.scala]: Because `table.profileTable` was declared as `Any`.

File: slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala [hunk 2]
```diff
@@ -136,6 +137,28 @@ class InsertTest extends AsyncTest[JdbcTestDB] {
     } yield ()
   }
 
+  def testInsertOrUpdatePlainWithFuncDefinedPK: DBIOAction[Unit, _, _] = {
+    //FIXME remove this after fixed checkInsert issue
+    if (tdb.profile.isInstanceOf[DerbyProfile]) return DBIO.successful(())
```
Comment (cvogt) [inline slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala]: so the way we handle this usually is capabilities.

Here is where you can define an appropriate one

https://github.com/slick/slick/blob/cada4176b2095563f113da540cc79eea0c7a39c3/slick/src/main/scala/slick/jdbc/JdbcCapabilities.scala#L15

here is where you exclude it from Derby to signal Derby does not support it

https://github.com/slick/slick/blob/6b59d0fc228bc4262491d0cf7110eaac0e0d8a7f/slick/src/main/scala/slick/jdbc/DerbyProfile.scala#L77

Here is how you can check for it in a test:

https://github.com/slick/slick/blob/898cb1871c610cea72027b266494f5bd83f770c9/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala#L82

The nice thing is that our docs list all of the limitations: http://slick.lightbend.com/doc/3.1.1/supported-databases.html (the list is generated automatically)

Would you mind adding one for this?

**Comment by cvogt** [comment]
Apart from the comment I like it :). Great work.

File: slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala (hunk 2 above)
Comment (tminglei) [inline slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala]: Well, we can't use `ifCap(jcap.insertOrUpdate)` here, since it will exclude some profiles, like `PostgresProfile`, `OracleProfile`, `SqliteProfile` from the test.

We only want to exclude derby here.

_p.s. I didn't see anything in http://slick.lightbend.com/doc/3.1.1/supported-databases.html need to be changed, since this fix won't add/remove any db feature._

Comment (cvogt) [inline slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala]: right, we'd need yet another capability like`insertOrUpdateWithFuncDefinedPK`. WDYT?

Comment (tminglei) [inline slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala]: No, I don't think so. It should be covered by `insertOrUpdate`.

**Comment by easel** [comment]
I'm curious on the status of this. I was going to try it out with my codebase, but since it's based on 3.2 and won't trivially backport to 3.1 I'm bailing out of that. 

Is the remaining issue the derby issue?

**Comment by mallyvai** [comment]
Curious about the state of this as well. We used this patch / fork to get around the insertOrUpdate bug. If it's not an issue anymore would love to not need to special-case this.

**Comment by cvogt** [comment]
I am ok with merging this. @szeiger @tminglei ?

**Comment by tminglei** [comment]
@cvogt I'd like to merge it in.

**Comment by cvogt** [comment]
LGTM. Go ahead, merge :).

**Comment by tminglei** [comment]
Merged.
