### PR TITLE
Replacing RegEx pattern matching. Fixes #1939

### LINKED ISSUE #1939: SQLite ModelBuilder Regex bug
I'm trying to extract a [db](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite_AutoIncrementPKs.sqlite) schema  to build tables models  
e.g. for this table:   
```SQL
CREATE TABLE [Invoice]
(
    -- ...
    [Total] NUMERIC(10,2)  NOT NULL,
    -- ...
);
```
and I got an exception:
```
scala.MatchError: NUMERIC(10,2) (of class java.lang.String)
	at slick.jdbc.SQLiteProfile$ModelBuilder$$anon$1.<init>(SQLiteProfile.scala:99)
	at slick.jdbc.SQLiteProfile$ModelBuilder.createColumnBuilder(SQLiteProfile.scala:94)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
	at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
	at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
	at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:171)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```  
I think that cased by this expression: 
https://github.com/slick/slick/blob/5013db0fb332379bcccad1f654f8c40b4ffbc7d7/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L99  
e.g. following test snippet recreates the original error:  
```Scala
scala> val TypePattern = "^([A-Z\\s]+)(\\(([0-9]+)\\))?$".r
TypePattern: scala.util.matching.Regex = ^([A-Z\s]+)(\(([0-9]+)\))?$

scala> "NUMERIC(10,2)" match {
     |           case TypePattern(d,_,s) => (d, Option(s).map(_.toInt))
     |           case "" => ("TEXT", None)
     |         }
scala.MatchError: NUMERIC(10,2) (of class java.lang.String)
  ... 39 elided
```  
as a workaround I wrote my own extension for `SQLiteProfile`  
with override for `createModelBuilder`  
where replaced RegEx pattern with this function:  
```scala
/** Regex matcher 
to extract name and length 
out of a db type name 
with length ascription */
def extract( 
  s: String = "NUMERIC(10,2)"
, pattern: scala.util.matching.Regex = "^([A-Z\\s]+)(\\(([0-9]+),?([0-9]+)?\\))?$".r
): ( String, Option[ Int ] ) = s match {
  case pattern( 
    name_Group, numeric_Group, integer_Group, fractional_Group 
  ) => ( name_Group, Option( integer_Group ).map( _.toInt ) )
  case "" => ( "TEXT", None )
}
private 
      val ( _dbType, _size ) = extract( 
        s = meta.typeName
      , pattern = "^([A-Z\\s]+)(\\(\\s?([0-9]+)\\s?,?\\s?([0-9]+)?\\s?\\))?$".r 
      )
```

### PR DESCRIPTION
**Pull request by GlulkAlex**
* Add new table defenition with Decimal_Types to sqlite.sql
* Add new asserts for DecimalTypes.baseTableRow in GeneratedCodeTest.scala
* Add extract_Type_Props def to ModelBuilder in SQLiteProfile.scala

### CODE REVIEW

**Comment by hvesalai** [comment]
Fixes #1939

**Comment by hvesalai** [comment]
@trevorsibanda is this ready to be merged?

**Comment by hvesalai** [comment]
There is a conflict. Can somebody please resolve?

**Comment by renatocaval** [comment]
Yep, I approved the change but didn't see the conflict. 
I can fix it.

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala [hunk 1]
```diff
@@ -95,12 +95,24 @@ trait SQLiteProfile extends JdbcProfile {
...
+      ): ( String, Option[ Int ] ) = s match {
+        case pattern( 
+          name, numericProps, precision, scale 
+        ) => ( name, Option( precision ).map( _.toInt ) )
+        case "" => ( "TEXT", None )
       }
+      private 
+      val ( _dbType, _size ) = extractTypeProps( 
+        s = meta.typeName
+      , pattern = "^([A-Z\\s]+)(\\(\\s?([0-9]+)\\s?,?\\s?([0-9]+)?\\s?\\))?$".r
```
Comment (renatocaval) [inline slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: @GlulkAlex, I don't think it is needed to have the pattern as a parameter to the `extractTypeProps`. 

We could keep it as:

```scala
final val TypePattern = "^([A-Z\\s]+)(\\(\\s?([0-9]+)\\s?,?\\s?([0-9]+)?\\s?\\))?$".r

def extractTypeProps(typeName: String = "NUMERIC(18,2)"): (String, Option[Int]) =
  typeName match {
    case TypePattern(name, _, precision, _) => (name, Option(precision).map(_.toInt) )
    case "" => ("TEXT", None)
  }
```

The return type `ColumnBuilder` and that method only exists on this specific anonymous instance and therefore is practically the equivalent of a `private` method. 

Since we have currently a merge conflict, and I offered myself to fix it, I will do that small change. Just wanted to let you know. Please, let me know if there were any particular reason for having it as a parameter. I may be missing something.

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala [hunk 2]
```diff
@@ -94,39 +94,48 @@ trait SQLiteProfile extends JdbcProfile {
...
+      /** Regex matcher to extract name and length
+       * out of a db type name with length ascription
+       */
+      def extractTypeProps(typeName: String = "NUMERIC(18,2)"): ( String, Option[ Int ] ) =
+        typeName match {
+          case TypePattern(name, _, precision, _) => ( name, Option( precision ).map( _.toInt ) )
+          case "" => ( "TEXT", None )
+        }
+
+      private val ( _dbType, _size ) = extractTypeProps(meta.typeName)
```
Comment (hvesalai) [inline slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: Using the underscore at the start of a name in Scala feels alien to me. Could it be without?

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala [hunk 3]
```diff
@@ -94,39 +94,48 @@ trait SQLiteProfile extends JdbcProfile {
...
             (s: String) => java.sql.Timestamp.valueOf(s),
             (s: String) => new java.sql.Timestamp(javax.xml.bind.DatatypeConverter.parseDateTime(s).getTime.getTime),
-      	    (s: String) => new java.sql.Timestamp(javax.xml.bind.DatatypeConverter.parseDateTime(s.replaceAll(" ","T")).getTime.getTime),
-      	    (s: String) => {
-      		    if(s == "now")
-      		      "new java.sql.Timestamp(java.util.Calendar.getInstance().getTime().getTime())"
-      		    else
-      		      throw new Exception(s"Failed to parse timestamp - $s")
-      	    }
+            (s: String) => new java.sql.Timestamp(javax.xml.bind.DatatypeConverter.parseDateTime(s.replaceAll(" ","T")).getTime.getTime),
```
Comment (hvesalai) [inline slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: `s.replace(' ', 'T')` or `s.replace(" ", "T")` would also work. The firs argument of replaceAll is a regex, so it requires compiling each time it is executed.

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala [hunk 4]
```diff
@@ -94,39 +94,48 @@ trait SQLiteProfile extends JdbcProfile {
...
+              else
+                throw new Exception(s"Failed to parse timestamp - $s")
+            }
           )
-      	  val v2 = v.replaceAll("\"", "")
-      	  convertors.collectFirst(fn => Try(fn(v2)) match{
-      	    case Success(v) => Some(v)
-      	  })
-      	}
+          val v2 = v.replaceAll("\"", "")
```
Comment (hvesalai) [inline slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: ditto here

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala (hunk 2 above)
Comment (renatocaval) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: @hvesalai, the code was already like that before this PR was made and I didn't want to introduce even more changes. 

It also disturbs me as many other poorly formatted pieces in the whole code base. I would prefer to tackle that in another PR. Maybe we should add scalafmt and have a clean-up hackathon.

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala (hunk 4 above)
Comment (renatocaval) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: This last one won't work. There is no `empty` char value that we could pass.

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala [hunk 5]
```diff
@@ -94,39 +94,48 @@ trait SQLiteProfile extends JdbcProfile {
...
 
     class ColumnBuilder(tableBuilder: TableBuilder, meta: MColumn) extends super.ColumnBuilder(tableBuilder, meta) {
-      /** Regex matcher to extract name and length out of a db type name with length ascription */
-      final val TypePattern = "^([A-Z\\s]+)(\\(([0-9]+)\\))?$".r
-      private val (_dbType,_size) = meta.typeName match {
-        case TypePattern(d,_,s) => (d, Option(s).map(_.toInt))
-        case "" => ("TEXT", None)
-      }
+
+      final val TypePattern = "^([A-Z\\s]+)(\\(\\s?([0-9]+)\\s?,?\\s?([0-9]+)?\\s?\\))?$".r
```
[the remark this answers is not in the document]
Comment (renatocaval) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: I tried this one and it's not working. I agree that if we only need `name` and `precision` we will can have a better pattern. 

I will invoke my RegEx supper powers* tomorrow morning to improve this. 

\* this is a joke, I'm terrible in RegEx

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala (hunk 4 above)
Comment (hvesalai) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: But there is `v.replace("\"", "")`

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala (hunk 2 above)
Comment (hvesalai) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: Ok

File: slick/src/main/scala/slick/jdbc/SQLiteProfile.scala (hunk 1 above)
Comment (GlulkAlex) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: @renatocaval As I can recall 
there is nothing special about having RegEx pattern as a parameter . 
It just looked more explicit and functional to me .

Comment (renatocaval) [reply slick/src/main/scala/slick/jdbc/SQLiteProfile.scala]: ok, fair enough. 

That's all very local, internal scope, so I prefer to simplify it as it will not be used in any other place.

**Comment by renatocaval** [comment]
Thanks @GlulkAlex! This is merged. We will cut 3.3 release ASAP.
