### PR TITLE
Fix Oracle escaping for createIfNotExists. Fixes #2151

### LINKED ISSUE #2151: Oracle field default string values not escaped correctly in createIfNotExists
If a table has been defined with String field(s) with default values, then createIfNotExists generates invalid DDL for Oracle, because the string constant for the default value is not escaped correctly for Oracle.

### PR DESCRIPTION
**Pull request by greenrd**

### CODE REVIEW

File: slick/src/main/scala/slick/jdbc/OracleProfile.scala [hunk 1]
```diff
@@ -171,7 +171,7 @@ trait OracleProfile extends JdbcProfile {
 BEGIN
 
 """+ ((createPhase1 ++ createPhase2).map{s =>
-      "execute immediate '"+ s.replaceAll("'", """\\'""") + " ';"
+      "execute immediate '"+ s.replaceAll("'", """''""") + " ';"
```
Comment (hvesalai) [inline slick/src/main/scala/slick/jdbc/OracleProfile.scala:174]: Since the escape no longer contains backslashes (\ ), there is no need to use the triple quotes ("""). Please change.

I don't know anything about Oracle, so can't verify if `'` should be quoted as `''`. Is there some documentation (or help forum article) you can point me to verify that.

Comment (greenrd) [reply slick/src/main/scala/slick/jdbc/OracleProfile.scala]: Changed.

There are two possible ways to do it, both covered [here](https://stackoverflow.com/a/11315369/495796).

**Comment by SethTisue** [comment]
@hvesalai re-review, merge?

**Comment by SethTisue** [comment]
but let's make sure CI likes it first

**Comment by SethTisue** [comment]
CI likes it

**Comment by hvesalai** [comment]
:shipit:
